// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: internal/proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PassKeeperService_AuthUser_FullMethodName     = "/internal.proto.PassKeeperService/AuthUser"
	PassKeeperService_RegisterUser_FullMethodName = "/internal.proto.PassKeeperService/RegisterUser"
	PassKeeperService_CreateData_FullMethodName   = "/internal.proto.PassKeeperService/CreateData"
	PassKeeperService_GetDataList_FullMethodName  = "/internal.proto.PassKeeperService/GetDataList"
	PassKeeperService_GetDataByID_FullMethodName  = "/internal.proto.PassKeeperService/GetDataByID"
	PassKeeperService_UpdateData_FullMethodName   = "/internal.proto.PassKeeperService/UpdateData"
	PassKeeperService_DeleteData_FullMethodName   = "/internal.proto.PassKeeperService/DeleteData"
)

// PassKeeperServiceClient is the client API for PassKeeperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PassKeeperServiceClient interface {
	AuthUser(ctx context.Context, in *UserAccountRequest, opts ...grpc.CallOption) (*UserAccountResponse, error)
	RegisterUser(ctx context.Context, in *UserAccountRequest, opts ...grpc.CallOption) (*UserAccountResponse, error)
	CreateData(ctx context.Context, in *CreateDataRequest, opts ...grpc.CallOption) (*CreateDataResponse, error)
	GetDataList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetDataResponse, error)
	GetDataByID(ctx context.Context, in *GetDataByIDRequest, opts ...grpc.CallOption) (*GetDataByIDResponse, error)
	UpdateData(ctx context.Context, in *UpdateDataRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*Empty, error)
}

type passKeeperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPassKeeperServiceClient(cc grpc.ClientConnInterface) PassKeeperServiceClient {
	return &passKeeperServiceClient{cc}
}

func (c *passKeeperServiceClient) AuthUser(ctx context.Context, in *UserAccountRequest, opts ...grpc.CallOption) (*UserAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAccountResponse)
	err := c.cc.Invoke(ctx, PassKeeperService_AuthUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passKeeperServiceClient) RegisterUser(ctx context.Context, in *UserAccountRequest, opts ...grpc.CallOption) (*UserAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAccountResponse)
	err := c.cc.Invoke(ctx, PassKeeperService_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passKeeperServiceClient) CreateData(ctx context.Context, in *CreateDataRequest, opts ...grpc.CallOption) (*CreateDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDataResponse)
	err := c.cc.Invoke(ctx, PassKeeperService_CreateData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passKeeperServiceClient) GetDataList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, PassKeeperService_GetDataList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passKeeperServiceClient) GetDataByID(ctx context.Context, in *GetDataByIDRequest, opts ...grpc.CallOption) (*GetDataByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataByIDResponse)
	err := c.cc.Invoke(ctx, PassKeeperService_GetDataByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passKeeperServiceClient) UpdateData(ctx context.Context, in *UpdateDataRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PassKeeperService_UpdateData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passKeeperServiceClient) DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PassKeeperService_DeleteData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassKeeperServiceServer is the server API for PassKeeperService service.
// All implementations must embed UnimplementedPassKeeperServiceServer
// for forward compatibility.
type PassKeeperServiceServer interface {
	AuthUser(context.Context, *UserAccountRequest) (*UserAccountResponse, error)
	RegisterUser(context.Context, *UserAccountRequest) (*UserAccountResponse, error)
	CreateData(context.Context, *CreateDataRequest) (*CreateDataResponse, error)
	GetDataList(context.Context, *Empty) (*GetDataResponse, error)
	GetDataByID(context.Context, *GetDataByIDRequest) (*GetDataByIDResponse, error)
	UpdateData(context.Context, *UpdateDataRequest) (*Empty, error)
	DeleteData(context.Context, *DeleteDataRequest) (*Empty, error)
	mustEmbedUnimplementedPassKeeperServiceServer()
}

// UnimplementedPassKeeperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPassKeeperServiceServer struct{}

func (UnimplementedPassKeeperServiceServer) AuthUser(context.Context, *UserAccountRequest) (*UserAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthUser not implemented")
}
func (UnimplementedPassKeeperServiceServer) RegisterUser(context.Context, *UserAccountRequest) (*UserAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedPassKeeperServiceServer) CreateData(context.Context, *CreateDataRequest) (*CreateDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateData not implemented")
}
func (UnimplementedPassKeeperServiceServer) GetDataList(context.Context, *Empty) (*GetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataList not implemented")
}
func (UnimplementedPassKeeperServiceServer) GetDataByID(context.Context, *GetDataByIDRequest) (*GetDataByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataByID not implemented")
}
func (UnimplementedPassKeeperServiceServer) UpdateData(context.Context, *UpdateDataRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateData not implemented")
}
func (UnimplementedPassKeeperServiceServer) DeleteData(context.Context, *DeleteDataRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteData not implemented")
}
func (UnimplementedPassKeeperServiceServer) mustEmbedUnimplementedPassKeeperServiceServer() {}
func (UnimplementedPassKeeperServiceServer) testEmbeddedByValue()                           {}

// UnsafePassKeeperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PassKeeperServiceServer will
// result in compilation errors.
type UnsafePassKeeperServiceServer interface {
	mustEmbedUnimplementedPassKeeperServiceServer()
}

func RegisterPassKeeperServiceServer(s grpc.ServiceRegistrar, srv PassKeeperServiceServer) {
	// If the following call pancis, it indicates UnimplementedPassKeeperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PassKeeperService_ServiceDesc, srv)
}

func _PassKeeperService_AuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassKeeperServiceServer).AuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassKeeperService_AuthUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassKeeperServiceServer).AuthUser(ctx, req.(*UserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassKeeperService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassKeeperServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassKeeperService_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassKeeperServiceServer).RegisterUser(ctx, req.(*UserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassKeeperService_CreateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassKeeperServiceServer).CreateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassKeeperService_CreateData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassKeeperServiceServer).CreateData(ctx, req.(*CreateDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassKeeperService_GetDataList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassKeeperServiceServer).GetDataList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassKeeperService_GetDataList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassKeeperServiceServer).GetDataList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassKeeperService_GetDataByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassKeeperServiceServer).GetDataByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassKeeperService_GetDataByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassKeeperServiceServer).GetDataByID(ctx, req.(*GetDataByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassKeeperService_UpdateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassKeeperServiceServer).UpdateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassKeeperService_UpdateData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassKeeperServiceServer).UpdateData(ctx, req.(*UpdateDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassKeeperService_DeleteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassKeeperServiceServer).DeleteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassKeeperService_DeleteData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassKeeperServiceServer).DeleteData(ctx, req.(*DeleteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PassKeeperService_ServiceDesc is the grpc.ServiceDesc for PassKeeperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PassKeeperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internal.proto.PassKeeperService",
	HandlerType: (*PassKeeperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthUser",
			Handler:    _PassKeeperService_AuthUser_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _PassKeeperService_RegisterUser_Handler,
		},
		{
			MethodName: "CreateData",
			Handler:    _PassKeeperService_CreateData_Handler,
		},
		{
			MethodName: "GetDataList",
			Handler:    _PassKeeperService_GetDataList_Handler,
		},
		{
			MethodName: "GetDataByID",
			Handler:    _PassKeeperService_GetDataByID_Handler,
		},
		{
			MethodName: "UpdateData",
			Handler:    _PassKeeperService_UpdateData_Handler,
		},
		{
			MethodName: "DeleteData",
			Handler:    _PassKeeperService_DeleteData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/proto.proto",
}
